// Re-export Void-generated Better Auth Drizzle tables from one stable path.
// Regenerated by `vp exec void prepare`.
export {
  userTable,
  sessionTable,
  accountTable,
  verificationTable,
} from "../../.void/better-auth-schema";
