name: Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
      - run: vp install
      - run: vp check
      - run: vp exec void deploy
        env:
          VOID_TOKEN: ${{ secrets.VOID_TOKEN }}
